version: '2'
services:
    adap_core-app:
        image: adap_core
        external_links:
            - adap_core-postgresql:postgresql
            - adap_core-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/adap_core
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    adap_core-postgresql:
        extends:
            file: postgresql.yml
            service: adap_core-postgresql
    adap_core-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: adap_core-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
